import { Poppins } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
// import { useEffect } from 'react'
// import AOS from 'aos';
// import 'aos/dist/aos.css'

const poppins = Poppins({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  // useEffect(() => {
  //   AOS.init({
  //     duration: 800,
  //     once: false,
  //   })
  // }, [])

  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
